spring:
    data:
        mongodb:
            database: homeautomation

server:
    port: 8080
    servletPath: /api

app:
    defaultUser:
        login: test
        password: $2a$10$m.sQIu0z9OL8DVuEsy8ta.wGC1tb8BMtlJ6fmuOx9u0nU0qVmUE/q
        homeId: home1

mqtt:
    broker:
        url: tcp://test.mosquitto.org:1883